### ISSUE TITLE
 puppet-fts changes

### ISSUE THREAD

**Issue by traylenator** [cernops/puppet-fts#4]
Hello,

Could you pls update puppet-fts with the new info below (we have rearranges packages so as BDII infosys and messaging to be optional to install)

1) remove $gfal2_repo, no longer needed
https://github.com/cernops/puppet-fts/blob/master/manifests/params.pp
https://github.com/cernops/puppet-fts/blob/master/manifests/install.pp

2) and separate infosys/msg packages to be installed (package{['fts-server','fts-client',"fts-${db_type}",'fts-libs','fts-monitoring','fts-infosys','fts-msg']:)
https://github.com/cernops/puppet-fts/blob/master/manifests/install.pp

3) add lcg-admin role in fts3config  (fts3config{'roles/lcgadmin':     value => 'vo:transfer'})
https://github.com/cernops/puppet-fts/blob/master/manifests/config.pp

Tnx,
Michail

**Comment by michailsal** [comment]
2)  and separate infosys/msg/fts-server-selinux packages to be installed:
(package{['fts-server','fts-client',"fts-${db_type}",'fts-libs','fts-monitoring','fts-infosys','fts-msg',,'fts-server-selinux']:)

**Comment by michailsal** [comment]
Tuesday's update:
-No need to drain, just apply puppet changes and update to version 3.2.22
Before you start the update, let me know to kill all active transfers so as to avoid long draining.

**Comment by traylenator** [comment]
All of these changes in latest release 0.0.5.
